### ISSUE TITLE
Translate action of a particular controller

### ISSUE THREAD

**Issue by jhonathas** [enriclluelles/route_translator#128] opened 2016-02-01 23:12 UTC
I can translate an action of a controller in particular.

Something like

```
routes:
    home: pagina_inicial
    contacts: contato
    new: novo
    makers:
        new: adicionar
```

**Comment by tagliala** [comment] 2016-02-02 11:26
Sorry, at the moment is not possible. 

Duplicate of #121

**Closed by tagliala** 2016-02-02 11:26 UTC
