### ISSUE TITLE
host_locales doesn't seem to be working

### ISSUE THREAD

**Issue by flaviomestre** [enriclluelles/route_translator#104] opened 2015-06-25 13:55 UTC
I'm trying to use route_translator with subdomains (en|pt|es.ityou.dev). I can make it work with a subfolder (ityou.dev/pt/) but subdomain won't work. I have the following:

```
# route_translator.rb
RouteTranslator.config.host_locales = {
	'en.ityou.*'     => :en,
	'pt.ityou.*'     => :pt,
	'es.ityou.*'     => :es
}
```

```
# routes.rb
localized do
    root 'static#home'
end
```

Any domain/subdomain I open always sets the locale to english
```
# open pt.ityou.dev:3000
Started GET "/" for 127.0.0.1 at 2015-06-25 08:51:43 -0500
Processing by StaticController#home as HTML
  Parameters: {"locale"=>"en"}
```

Am I missing something?

**Comment by tagliala** [comment] 2015-06-25 15:55
you are probably missing this one: #95

Ok, I'm a collaborator, but I don't know how to solve this :)

Closing here, please share your thoughts in #95. If it is not the same issue feel free to comment here

**Closed by tagliala** 2015-06-25 15:55 UTC

**Comment by flaviomestre** [comment] 2015-06-25 16:22
Hi @tagliala thanks for commenting.

From what I understanding, #95 is about generating the right routes. In my case, I'm having trouble getting the locale correctly assigned from the subdomain.

Did I understand right?

Did you get the subdomain locale detection to work on your side?

**Comment by tagliala** [comment] 2015-06-25 16:27
I think that the issue I'm having is the same issue as yours, because I don't get the exact locale in the root path, and it is probably the cause of the wrong urls: 

> when I visit http://it.lvh.me:3000 I can't see the Italian translation, because something is messing up with the :locale param

I'm using a custom solution at the moment. Just skipped `host_locales` and implemented by myself in an around filter

**Comment by flaviomestre** [comment] 2015-06-25 16:37
Can you share how you solved the locale detection from subdomain? I read the issues you posted but couldn't find any that worked for me.

**Comment by tagliala** [comment] 2015-06-25 18:57
Something like this:


`route_translator.rb`
```
RouteTranslator.config do |config|
  config.hide_locale = true
end
```

`development.rb`
```rb
  # Map domains to languages
  DOMAIN_LANGUAGE = {
    'it.lvh.me' => :it,
    'en.lvh.me' => :en,
    'de.lvh.me' => :de
  }
```

`application_controller.rb`
```rb
  skip_around_action :set_locale_from_url
  around_action :set_site_locale

  def set_site_locale(&block)
    I18n.with_locale DOMAIN_LANGUAGE[request.host], &block
  end
```
