### ISSUE TITLE
locale param is always overriden in tests in controllers

### ISSUE THREAD

**Issue by michaldarda** [enriclluelles/route_translator#177] opened 2017-11-23 22:28 UTC
```
    it 'redirects to correct one' do
      get '/courses/search_results', locale: 'pt'

      expect(response.code).to eq '301'
    end
```

This spec does not work, I have always locale set to en in my controller, can't override

Rails 4.2.10, route_translator-4.4.1

**Comment by tagliala** [comment] 2017-12-31 13:02
Hi,

I'm going to close this because I don't want to maintain the 4.x version.

If this is still an issue on the latest version, please let me know and I will reopen.

Also, please provide more information, in terms of expected behaviour and actual behavior

Closing here

**Closed by tagliala** 2017-12-31 13:02 UTC
