### ISSUE TITLE
`hide_locale=true` not working for `host_locales`

### ISSUE THREAD

**Issue by xpepermint** [enriclluelles/route_translator#101] opened 2015-05-02 14:26 UTC
I set `host_locales` configuration option and `force_locale=true` thus the `:locale` will not be visible but all my subdomains have `:locale` attached. 

```ruby
RouteTranslator.config do |config|
  config.host_locales = {
    'si.*' => :sl,
    'hr.*' => :hr,
    'ro.*' => :ro
    # default to :en
  }
  config.hide_locale = true
end
```
Navigating to `hr.domain.com` and calling `about_path` helper will generate `/hr/about` instead of `/about`.

**Comment by tagliala** [comment] 2015-05-02 15:24
Duplicate of #95, let's talk there

**Closed by tagliala** 2015-05-02 15:24 UTC

**Comment by xpepermint** [comment] 2015-05-02 15:26
Ow, sorry... ok
