### ISSUE TITLE
Routes are generated small-caps 

### ISSUE THREAD

**Issue by pawelkomarnicki** [enriclluelles/route_translator#176] opened 2017-11-03 10:59 UTC
For dialect locales like en-US, routes are generated as /en-us/, instead of how they should be /en-US/

**Comment by tagliala** [comment] 2017-11-03 11:06
Duplicate of #168 

Ref: https://github.com/enriclluelles/route_translator/issues/168#issuecomment-312435650

Hope it helps

**Closed by tagliala** 2017-11-03 11:06 UTC
