### ISSUE TITLE
Missing translated routes in development after routes_reloader.reload!

### ISSUE THREAD

**Issue by dssjoblom** [enriclluelles/route_translator#252] opened 2021-10-01 13:36 UTC
This issue does not happen often, in fact, I've only seen it happen once exactly. Sometimes the URL generation methods fail. Running the exact same code a moment later works, so I'm assuming it is something related to multi-threading or other unexpected state corruption. 

### Expected behavior*
xxx_yyy_de_url should generate the German URL for xxx_yyy. This works correctly 99.99% of the time.

### Actual behavior*
Sometimes, however, the route generation fails with:

undefined method `xxx_yyy_de_url'

stacktrace:

gems/route_translator-10.0.0/lib/route_translator/translator/route_helpers.rb:35
[customer code that tries to generate URL omitted]

If it makes any difference, the call is made from a Rails mailer, not from a regular view template.

### System configuration*
**Rails version**: 5.1.7
**Ruby version**: 2.5.5p157
**Route Translator version**: 10.0.0

### Route Translator initializier

Source of: `config/initializers/route_translator.rb`

```rb
RouteTranslator.config do |config|
  config.hide_locale = true
  config.disable_fallback = true
end
```

I can provide more details upon request, however, the route and localization files etc. are confidential and also too large to share here. The correct routes are definitely present, as the code works almost always.

**Comment by tagliala** [comment] 2021-10-01 16:13
> I can provide more details upon request, however, the route and localization files etc. are confidential and also too large to share here. The correct routes are definitely present, as the code works almost always.

Any chance to setup a new rails application with the bare minimum amount of code to try to reproduce this issue?

**Comment by dssjoblom** [comment] 2022-01-25 07:40
@tagliala if you are still looking into this, I was now able to consistently reproduce the issue. The test case is too large/confidential to share, but the root cause is that in our app we call Rails.application.routes_reloader.reload! under specific (rare) circumstances. This seems to not work correctly with RouteTranslator.

**Comment by tagliala** [comment] 2022-01-25 07:44
Thanks. This has not been reported by other users, but if you manage to create a reproducible test case, we can check if it can be fixed or it should be listed as a known issue

**Comment by tagliala** [comment] 2023-08-05 10:28
Closing here because of missing reproducible test case

**Closed by tagliala** 2023-08-05 10:28 UTC
Labels: help wanted, need feedback
