### ISSUE TITLE
locale path segment not added to translated route (multiple languages on the same host with host locale translation enabled)

### ISSUE THREAD

**Issue by dbwinger** [enriclluelles/route_translator#288] opened 2023-07-27 14:57 UTC
### Steps to reproduce*
This is maybe more a question.  Maybe I'm misunderstanding how it should work.

### Expected behavior*
Request to `http://127.0.0.1/products/npe180-a2` should set `I18n.locale` to `en-CA` and route to `ProductsController`.  It does.
Request to `http://127.0.0.1/fr-CA/produits/npe-180a2` should set `I18n.locale` to `en-FR` and route to `ProductsController`.  

### Actual behavior*
NOTE:  I am using AlchemyCMS which may or may not play into how this is working...
The second request above does correctly set `I18n.locale` to `fr-CA`, but does not route to `ProductsController`, instead routing to my `Alchemy::Engine` route.
Additionally, from the page served by the `Alchemy` route, `product_path('npe-180a2')`, `product_path('npe-180a2', locale: 'fr-CA')`, and `product_fr_ca_path('npe-180a2', locale: 'fr-CA')` all return "/produits/npe-180a2", lacking the locale url segment.

What I'm wanting is that paths without the locale segment use `en-CA` and that routes generated also don't include the locale segment and all paths with the `fr-CA` locale segment and translated routes to be handled by the correct controllers and that urls generated in responses to those requests to also automatically have the `/fr-CA/` locale segment unless another locale is specified.  This was actually working as expected under your v9, but I need to update in order to update the app to Rails 7.

### System configuration*
**Rails version**:
Rails 6.1.7.4
**Ruby version**:
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]
**Route Translator version**:
route_translator (13.1.1)

### I18n configuration*
```rb
I18n.available_locales = [:en, :es, :"en-CA", :"fr-CA"]
I18n.default_locale = :en

require "i18n/backend/fallbacks" 
I18n::Backend::Simple.send(:include, I18n::Backend::Fallbacks)
I18n.fallbacks.map("fr-CA": :"en-CA")
```

### Route Translator initializier
```rb
RouteTranslator.config do |config|
  config. host_locales={"127.0.0.1"=>:"en-CA"}
  config.locale_segment_proc = ->(locale) {
    # If there's a country code, use format fr-CA
    "#{[locale.to_s.split('-').first.downcase, locale.to_s.split('-').second&.upcase].compact.join('-')}"
  }
end
```

### Source code of routes.rb*

```rb
Rails.application.routes.draw do
  localized do
    resources :products
    ...
  end
  ...
  mount Alchemy::Engine => '/'
end
```

### Locale `.yml` files*

`config/locales/fr-CA.yml`:
```yml
fr-CA:
  routes:
    products: produits
```

`config/locales/en-CA.yml`:
```yml
en-CA:
  routes:
    products: products
```

### Output of `rails routes`*

Result of `bundle exec rails routes`:

```
...
                                                 product_es GET                 /productos/:id(.:format)                      products#show {:locale=>"es"}
                                               product_en_ca GET                 /products/:id(.:format)                    products#show {:locale=>"en-CA"}
                                               product_fr_ca GET                 /produits/:id(.:format)                      products#show {:locale=>"fr-CA"}
                                                  product_en GET                 /products/:id(.:format)                      products#show {:locale=>"en"}
...
```

### Repository demonstrating the issue

This is happening in a private repo.  If necessary I can try to create a simple example app, but I'm first of all just seeking to know whether I'm understanding the intended behavior correctly. Thanks!
---

**\*** Failure to include this requirement may result in the issue being closed.

**Comment by tagliala** [comment] 2023-07-27 16:07
Hi, thanks for the detailed report but I still can't understand it properly. As far as I got this is a regression (or a wanted breaking change) from an older version

> This was actually working as expected under your v9

Can you please `git bisect` to the change that broke this behavior?

All version from v9 to v13 should support 6.1

I suspect it may be one of  #91, #171, #87 released in v10

**Comment by dbwinger** [comment] 2023-08-02 18:23
Thank you so much for the quick reply!  I've decided I think my best course of action is to branch off v9, and apply the applicable fixes/updates since then, but not the functionality changes, and maintain that branch myself.  I need the functionality of multiple languages on a single subdomain.

**Comment by tagliala** [comment] 2023-08-05 10:21
Closing here as wontfix. This is an intended change

Ref: #171

> If you have special needs (eg: main domain with all languages, subdomains with separate languages) please go for a custom solution.
> 
> Having multiple languages for the same subdomain is out of the Route Translator's scope.

**Closed by tagliala** 2023-08-05 10:21 UTC
Labels: wontfix
